<a href="https://colab.research.google.com/github/ArelyA/CE888_2020_Data-Science/blob/master/Labs/CE888_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CE888: Data Science and Decision Making
## Lab 1 (15.01.2020)

In [0]:
import numpy as np
import random

#### Create a (4 x 2) integer array and print it's attributes

In [0]:
arr = np.array([[random.randint(1, 20) for y in range(2)] for x in range(4)])
print(arr)

[[ 2  7]
 [ 3 18]
 [ 1 16]
 [15 17]]


#### Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
arr2 = np.array([random.randint(1, 20) for x in range(10)])

print(arr2)

arr2 = np.sort(arr2)[::-1]
print(arr2)

arr2 = np.sort(arr2)
print(arr2)

[ 5 13 18  4 18  6 19 10 19  9]
[19 19 18 18 13 10  9  6  5  4]
[ 4  5  6  9 10 13 18 18 19 19]


#### Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
arr3 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr3 = np.reshape(arr3, (3, 3))
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Stack two arrays of any size horizontally and vertically

In [0]:
arrTemp = arr3 + random.randint(1, 20)
print(arrTemp, '\n')
arr4 = np.hstack((arrTemp, arr3))
print(arr4, '\n')
arr5 = np.vstack((arrTemp, arr3))
print(arr5)

[[ 7  8  9]
 [10 11 12]
 [13 14 15]] 

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]
 [13 14 15  7  8  9]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


#### Create two array of same size and find commom elements

In [0]:
size = random.randint(1, 15)
arr6 = np.array([random.randint(1, 20) for x in range(size)])
print(arr6)
arr7 = np.array([random.randint(1, 20) for x in range(size)])
print(arr7)
print(np.intersect1d(arr6.flatten(), arr7.flatten()))

[18  2  9  9  9 14  8 15  9]
[ 7 20 12  5  6 13  9  9 10]
[9]


#### Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
arr8 = np.array([[random.randint(1, 20) for y in range(5)] for x in range(5)])
print(arr8)
for index, x in enumerate(arr8):
    print('\nrow %d'%index)
    print('Max val', np.amax(x))
    print('Min val', np.amin(x))

[[ 9  4 19 20 12]
 [20 20 18  8 18]
 [10  9 11  5  9]
 [ 5 19 19 12 20]
 [14 13 13  6  1]]

row 0
Max val 20
Min val 4

row 1
Max val 20
Min val 8

row 2
Max val 11
Min val 5

row 3
Max val 20
Min val 5

row 4
Max val 14
Min val 1


#### Create an array of size 100 and compute the mean, median, standard deviation.

In [0]:
arr9 = np.random.random(100)
print(arr9)
print("Mean: %f"%np.mean(arr9), "Median: %f"%np.median(arr9), "Standard Deviation: %f"%np.std(arr9), sep = '\n')

[0.17396608 0.55829884 0.66208479 0.29715988 0.03250854 0.27399086
 0.37172688 0.83553818 0.21362963 0.29390976 0.69726472 0.24397839
 0.19698404 0.31719013 0.71984052 0.40481898 0.01268797 0.69448705
 0.68732162 0.13152359 0.70893991 0.05436392 0.91250802 0.75098603
 0.05402251 0.6365958  0.96156469 0.33037231 0.49234795 0.8205805
 0.76006675 0.04141193 0.90605672 0.16733026 0.13567383 0.53285899
 0.87425807 0.34324539 0.31218462 0.67655897 0.80369191 0.26741323
 0.06912633 0.09974465 0.60994789 0.6621331  0.97737712 0.28536117
 0.02849438 0.55004709 0.7990937  0.04999189 0.16605585 0.46760265
 0.41412841 0.12435347 0.89119532 0.61961026 0.61262158 0.19140995
 0.20648404 0.64739262 0.34961551 0.41423566 0.70064401 0.88897372
 0.61871016 0.75725135 0.54349966 0.99540324 0.22180377 0.91431421
 0.67551859 0.90833911 0.03778926 0.93450613 0.94705516 0.99724174
 0.78284396 0.24242917 0.69535009 0.69145388 0.25992515 0.35403359
 0.0710877  0.46095518 0.43285218 0.47111872 0.90201924 0.46110

#### Normalize a 5x5 random matrix

In [0]:
arr10 = np.array([[random.randint(1, 20) for y in range(5)] for x in range(5)])
print(arr10)
min10 = arr10.min()
max10 = arr10.max()
arr10 = (arr10 - min10)/(max10 - min10)
print('\n', arr10)

[[13 17 15  4  2]
 [ 2  5 12  8 12]
 [ 8  6  8 13  5]
 [ 2 12  4  1  1]
 [ 9  5 19  7  9]]

 [[0.66666667 0.88888889 0.77777778 0.16666667 0.05555556]
 [0.05555556 0.22222222 0.61111111 0.38888889 0.61111111]
 [0.38888889 0.27777778 0.38888889 0.66666667 0.22222222]
 [0.05555556 0.61111111 0.16666667 0.         0.        ]
 [0.44444444 0.22222222 1.         0.33333333 0.44444444]]


#### Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [0]:
arr11 = np.array([[[1, 2, 3]]* 4] * 4)
print('arr11 before reshape\n', arr11)
arr11 = arr11.reshape(3, 4, 4)
print('arr11 after reshape\n', arr11)
arr12 = np.array([[1, 2, 3, 4]]* 4)
print('\n arr12\n', arr12)
print('\n Result\n', np.dot(arr11, arr12))

arr11 before reshape
 [[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
arr11 after reshape
 [[[1 2 3 1]
  [2 3 1 2]
  [3 1 2 3]
  [1 2 3 1]]

 [[2 3 1 2]
  [3 1 2 3]
  [1 2 3 1]
  [2 3 1 2]]

 [[3 1 2 3]
  [1 2 3 1]
  [2 3 1 2]
  [3 1 2 3]]]

 arr12
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

 Result
 [[[ 7 14 21 28]
  [ 8 16 24 32]
  [ 9 18 27 36]
  [ 7 14 21 28]]

 [[ 8 16 24 32]
  [ 9 18 27 36]
  [ 7 14 21 28]
  [ 8 16 24 32]]

 [[ 9 18 27 36]
  [ 7 14 21 28]
  [ 8 16 24 32]
  [ 9 18 27 36]]]
